### ISSUE TITLE
The telegram guide seems to be outdated

### ISSUE THREAD

**Issue by Klingefjord** [privacyint/website-guides#26]
Trying to export my data from telegram, but there is no option for it in the settings and the layout is different from the guide
<img width="705" alt="Screen Shot 2022-04-12 at 16 09 00" src="https://user-images.githubusercontent.com/22666776/162981283-db74616e-150f-4577-b8e9-5ef83a29f15b.png">
:

**Comment by EBendinelli** [comment]
Hi @Klingefjord, thanks for flagging this. Could you please let us know what device, Operating System and version of Telegram you are using?

We believe this feature is only available for the desktop client on MacOS, Windows and Linux but there might be other way to obtain this data

**Comment by EBendinelli** [comment]
Guides [clearly indicates](https://github.com/privacyint/website-guides/blob/master/guide-steps/en/guide-getting-your-data-telegram.md?plain=1#L18) that the desktop version is required to download your data. Closing this issue after 15 days.

**Comment by Klingefjord** [comment]
This was the desktop version
